### ISSUE TITLE
로그인 시 503 에러 발생

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/osu-BeatmapMirror#2]
19일부터 발생... 해결 방법이 어찌되는가....

**Comment by mxxive** [comment]
로그인할 때 발생하는 CloudFlare 관련 오류라면... Cloudflare-bypass 때문이 아닐까 하고 예상해봅니다...
어디에서 문제가 발생하고 있는건지 파악이 안 되서 그냥 예상되는 점만 올립니다.
이 기능은 cloudflare에서 제공하는 여러가지 크라울링 방지 기능 중 한가지라고 알고 있습니다.

만약 이 기능 때문에 발생하는 오류가 맞다면,
이 기능은 특정 페이지를 보여주고, javascript로 된 문제를 주어준 뒤, 일정 시간 안에 문제를 풀어서 제출해야지 원하는 페이지를 보여주는 기능입니다.
해결 방법은 3가지 정도 있는데,
첫 번째는 자바스크립트 부분을 긁어서 로컬에서 node.js나 C#의 JInt 같이 자바스크립트를 실행할 수 있는 프로그램으로 문제의 답을 얻고 제출하는 것.
두 번째는 selenium같이 javascript가 가능한 브라우저를 사용해서 스크롤을 하는 것
세 번째는 cfscrape 같은 라이브러리를 이용하는 방법입니다. 주어지는 문제가 일정 주기로 계속 바뀌는 걸로 알고 있습니다. 그러므로 가급적이면 계속해서 업데이트가 이뤄지는 라이브러리를 이용하시길 추천드립니다.
