### ISSUE TITLE
로그인 시 Set-Cookie로 로그인 여부 확인 불가능

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/osu-BeatmapMirror#5]

**Comment by mirusu400** [comment]
오스에서 로그인시 체크하는 쿠키가
- `osu_session`
- `phpbb3_2cjk5_u`
- `phpbb3_2cjk5_sid`
- `phpbb3_2cjk5_sid_check`
이거 네개인 거 같은데

https://github.com/sunghwan2789/osu-BeatmapMirror/blob/e86d561db2a43b7fbccc4b006ab9dd4e7fdfa421/Manager/Client.cs#L118-L136

이 부분의 소스코드에서 위 네개의 쿠키를 모두 가져오도록 수정하면 되지 않을까요?


```diff
++ { "sid_check", Request.GetCookie("phpbb3_2cjk5_sid_check")}
++ { "session_id", Request.GetCookie("osu_session") },
```

그리고 추가로 다운로드 시 사용하는 주소도 업데이트가 된거 같습니다.


https://github.com/sunghwan2789/osu-BeatmapMirror/blob/e86d561db2a43b7fbccc4b006ab9dd4e7fdfa421/Utility/Request.cs#L141

```diff
-- using (var response = await Client.GetAsync($"https://osu.ppy.sh/d/{id}", HttpCompletionOption.ResponseHeadersRead))
++ using (var response = await Client.GetAsync($"https://osu.ppy.sh/beatmapsets/{id}/download", HttpCompletionOption.ResponseHeadersRead))
```

**Comment by sunghwan2789** [comment]
지금 확인해보니 username, password가 모두 맞음에도 incorrect password 메시지를 주네요...
대체 뭐가 문제인지...

**Comment by sunghwan2789** [comment]
인증 절차에 Referrer 검증이 추가되었네요.
또, 로그인 성공 시 redirection 진행으로 `Set-Cookie` 헤더 자체를 숨기네요.
`CookieContainer`에서 로그인 여부 확인하는 거로 바꿔볼게요.
